name: setuback
description: Bug and Feedback report app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-114.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.4
  google_fonts: ^3.0.1

  # Utils
  shared_preferences: ^2.0.15
  intl: ^0.17.0

  # Network
  graphql: ^5.1.1
  dio: ^4.0.6
  internet_connection_checker: ^0.0.1+4

  # Logic
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
